// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SleepTracker.Data;

#nullable disable

namespace SleepTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260410082842_AddFactorValue")]
    partial class AddFactorValue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("SleepTracker.Models.SleepFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SleepLogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SleepLogId");

                    b.ToTable("SleepFactors");
                });

            modelBuilder.Entity("SleepTracker.Models.SleepLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SleepEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SleepStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SleepLogs");
                });

            modelBuilder.Entity("SleepTracker.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SleepTracker.Models.SleepFactor", b =>
                {
                    b.HasOne("SleepTracker.Models.SleepLog", "SleepLog")
                        .WithMany("Factors")
                        .HasForeignKey("SleepLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SleepLog");
                });

            modelBuilder.Entity("SleepTracker.Models.SleepLog", b =>
                {
                    b.HasOne("SleepTracker.Models.User", "User")
                        .WithMany("SleepLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SleepTracker.Models.SleepLog", b =>
                {
                    b.Navigation("Factors");
                });

            modelBuilder.Entity("SleepTracker.Models.User", b =>
                {
                    b.Navigation("SleepLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
